### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by AyyItzJ4y** [FreakingDev/PHC-SimpleForm#3]
Alam mo po ba kong mag hold ka nang block sa air mag open nang form, kong alam mo po please sabihin mo salamat!

**Comment by AyyItzJ4y** [comment]
In english do you know how to execute a command when you click and hold a item in the air it executes a command

**Comment by FreakingDev** [comment]
Using PHC-SimpleForm. Write this code to your plugin

// use this library
use pocketmine\event\player\PlayerInteractEvent;

// Change the item ID to anything you want
public function onInteract(PlayerInteractEvent $event){
		$player = $event->getPlayer();
		$item = $event->getItem();
		
		if($item->getId() == 369){
			$command = "phcui";
			$this->getServer()->getCommandMap()->dispatch($event->getPlayer(), $command);
		}
		
}
